[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
gifportal = "GWXJMUTKETCdfGMYN7dgXAtu3831oaxLNz95u4risCfQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/root/.config/solana/new-keypair.json"

[scripts]
test = "node tests/gifportal.js"
