[toolchain]

[features]
resolution = true
skip-lint = false

[programs.testnet]
gifportal = "GWXJMUTKETCdfGMYN7dgXAtu3831oaxLNz95u4risCfQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Testnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "node tests/gifportal.js"
